extensions:
  mcp_my-server:
    enabled: true
    name: mcp_my-server
    type: streamable_http
    uri: https://api.example.com/mcp/default
    envs: {}
    env_keys: []
    headers: {}
    description: ''
    timeout: 300
    bundled: null
    available_tools: []
